/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.example.demo

import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.autoconfigure.EnableAutoConfiguration
import org.springframework.boot.runApplication

@SpringBootApplication
//@EnableAutoConfiguration
class App

fun main(args: Array<String>) {
    //val tokens = StringUtils.split(MessageUtils.getMessage())
    //val result = StringUtils.join(tokens)
    //println(WordUtils.capitalize(result))
    runApplication<App>(*args)

}
