name: ci

on:
  workflow_dispatch:

jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - uses: snyk/actions/setup@master
      
    - name: Build with Gradle
      run: gradle build
    
    - name: run Snyk Code Test
      run: snyk code test azure-vote/
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  unittest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
        
      
    - name: Build with Gradle
      run: gradle test
    
