name: Java CI with Gradle


on:
  workflow_dispatch:

jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with: 
        languages: java
      
    - name: Build with Gradle
      run: gradle build
    
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2

  unittest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
        
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with: 
        languages: java
      
    - name: Build with Gradle
      run: gradle test
    
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
